import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import { nitro } from "nitro/vite";
import { defineConfig } from "vite";

export default defineConfig({
  server: {
    host: "127.0.0.1",
    port: 3000,
    strictPort: true,
  },
  resolve: {
    tsconfigPaths: true,
  },
  plugins: [
    tanstackStart({
      router: {
        quoteStyle: "double",
        semicolons: true,
        routeTreeFileHeader: [
          "// biome-ignore-all lint: generated by TanStack Router\n// biome-ignore-all assist/source/organizeImports: generated by TanStack Router\n// biome-ignore-all format: generated by TanStack Router\n// @ts-nocheck",
        ],
      },
      spa: {
        enabled: true,
      },
    }),
    nitro(),
    viteReact(),
    tailwindcss(),
  ],
});
