import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import { nitro } from "nitro/vite";
import { defineConfig, loadEnv } from "vite";
import {
  appendForwardedPeer,
  getApiProxyTarget,
} from "./src/server/api-upstream";

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), "API_UPSTREAM_URL");
  const upstream =
    process.env.API_UPSTREAM_URL ||
    env.API_UPSTREAM_URL ||
    "http://127.0.0.1:3001";
  getApiProxyTarget("/api/auth/get-session", upstream);
  return {
    server: {
      host: "127.0.0.1",
      port: 3000,
      strictPort: true,
      proxy: {
        "^/api/(auth|v4)(/|$)": {
          target: upstream,
          changeOrigin: true,
          followRedirects: false,
          configure: (proxy) => {
            proxy.on("proxyReq", (request, incoming) => {
              // Always anchor the forwarding chain in the actual TCP peer.
              // The backend walks right-to-left through its explicit proxy CIDRs.
              try {
                request.setHeader(
                  "x-forwarded-for",
                  appendForwardedPeer(
                    typeof incoming.headers["x-forwarded-for"] === "string"
                      ? incoming.headers["x-forwarded-for"]
                      : undefined,
                    incoming.socket.remoteAddress,
                  ),
                );
              } catch {
                request.destroy(new Error("Proxy client address unavailable"));
              }
              request.removeHeader("x-real-ip");
              request.removeHeader("x-video-host-client-ip");
              request.removeHeader("forwarded");
              request.removeHeader("x-forwarded-host");
              request.removeHeader("x-forwarded-proto");
            });
          },
        },
      },
    },
    resolve: {
      tsconfigPaths: true,
    },
    plugins: [
      tanstackStart({
        router: {
          quoteStyle: "double",
          semicolons: true,
          routeTreeFileHeader: [
            "// biome-ignore-all lint: generated by TanStack Router\n// biome-ignore-all assist/source/organizeImports: generated by TanStack Router\n// biome-ignore-all format: generated by TanStack Router\n// @ts-nocheck",
          ],
        },
        spa: {
          enabled: true,
        },
      }),
      nitro({
        serverDir: "./src/server",
      }),
      viteReact(),
      tailwindcss(),
    ],
  };
});
