// biome-ignore-all lint: generated by TanStack Router
// biome-ignore-all assist/source/organizeImports: generated by TanStack Router
// biome-ignore-all format: generated by TanStack Router
// @ts-nocheck

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AppRouteImport } from "./routes/_app";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as RegisterRouteImport } from "./routes/register";
import { Route as AppIndexRouteImport } from "./routes/_app.index";
import { Route as AppDashboardRouteImport } from "./routes/_app.dashboard";
import { Route as AppHistoryRouteImport } from "./routes/_app.history";
import { Route as ApiHealthzRouteImport } from "./routes/api.healthz";
import { Route as AppDashboardIndexRouteImport } from "./routes/_app.dashboard.index";
import { Route as AppMoviesMovieRouteImport } from "./routes/_app.movies.$movie";
import { Route as AppSearchQueryRouteImport } from "./routes/_app.search.$query";
import { Route as AppSeriesSeriesRouteImport } from "./routes/_app.series.$series";
import { Route as AppUsersUserRouteImport } from "./routes/_app.users.$user";
import { Route as AppDashboardAdminSystemAccountsRouteImport } from "./routes/_app.dashboard.admin.system-accounts";
import { Route as AppDashboardPlaylistsIndexRouteImport } from "./routes/_app.dashboard.playlists.index";
import { Route as AppDashboardPlaylistsNewRouteImport } from "./routes/_app.dashboard.playlists.new";
import { Route as AppDashboardSeriesIndexRouteImport } from "./routes/_app.dashboard.series.index";
import { Route as AppDashboardSeriesNewRouteImport } from "./routes/_app.dashboard.series.new";
import { Route as AppDashboardVideosIndexRouteImport } from "./routes/_app.dashboard.videos.index";
import { Route as AppDashboardVideosNewRouteImport } from "./routes/_app.dashboard.videos.new";
import { Route as AppDashboardPlaylistsIdEditRouteImport } from "./routes/_app.dashboard.playlists.$id.edit";
import { Route as AppDashboardSeriesIdEditRouteImport } from "./routes/_app.dashboard.series.$id.edit";
import { Route as AppDashboardVideosIdEditRouteImport } from "./routes/_app.dashboard.videos.$id.edit";

const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRoute,
} as any);
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => AppRoute,
} as any);
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: "/api/healthz",
  path: "/api/healthz",
  getParentRoute: () => rootRouteImport,
} as any);
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppDashboardRoute,
} as any);
const AppMoviesMovieRoute = AppMoviesMovieRouteImport.update({
  id: "/movies/$movie",
  path: "/movies/$movie",
  getParentRoute: () => AppRoute,
} as any);
const AppSearchQueryRoute = AppSearchQueryRouteImport.update({
  id: "/search/$query",
  path: "/search/$query",
  getParentRoute: () => AppRoute,
} as any);
const AppSeriesSeriesRoute = AppSeriesSeriesRouteImport.update({
  id: "/series/$series",
  path: "/series/$series",
  getParentRoute: () => AppRoute,
} as any);
const AppUsersUserRoute = AppUsersUserRouteImport.update({
  id: "/users/$user",
  path: "/users/$user",
  getParentRoute: () => AppRoute,
} as any);
const AppDashboardAdminSystemAccountsRoute =
  AppDashboardAdminSystemAccountsRouteImport.update({
    id: "/admin/system-accounts",
    path: "/admin/system-accounts",
    getParentRoute: () => AppDashboardRoute,
  } as any);
const AppDashboardPlaylistsIndexRoute =
  AppDashboardPlaylistsIndexRouteImport.update({
    id: "/playlists/",
    path: "/playlists/",
    getParentRoute: () => AppDashboardRoute,
  } as any);
const AppDashboardPlaylistsNewRoute =
  AppDashboardPlaylistsNewRouteImport.update({
    id: "/playlists/new",
    path: "/playlists/new",
    getParentRoute: () => AppDashboardRoute,
  } as any);
const AppDashboardSeriesIndexRoute = AppDashboardSeriesIndexRouteImport.update({
  id: "/series/",
  path: "/series/",
  getParentRoute: () => AppDashboardRoute,
} as any);
const AppDashboardSeriesNewRoute = AppDashboardSeriesNewRouteImport.update({
  id: "/series/new",
  path: "/series/new",
  getParentRoute: () => AppDashboardRoute,
} as any);
const AppDashboardVideosIndexRoute = AppDashboardVideosIndexRouteImport.update({
  id: "/videos/",
  path: "/videos/",
  getParentRoute: () => AppDashboardRoute,
} as any);
const AppDashboardVideosNewRoute = AppDashboardVideosNewRouteImport.update({
  id: "/videos/new",
  path: "/videos/new",
  getParentRoute: () => AppDashboardRoute,
} as any);
const AppDashboardPlaylistsIdEditRoute =
  AppDashboardPlaylistsIdEditRouteImport.update({
    id: "/playlists/$id/edit",
    path: "/playlists/$id/edit",
    getParentRoute: () => AppDashboardRoute,
  } as any);
const AppDashboardSeriesIdEditRoute =
  AppDashboardSeriesIdEditRouteImport.update({
    id: "/series/$id/edit",
    path: "/series/$id/edit",
    getParentRoute: () => AppDashboardRoute,
  } as any);
const AppDashboardVideosIdEditRoute =
  AppDashboardVideosIdEditRouteImport.update({
    id: "/videos/$id/edit",
    path: "/videos/$id/edit",
    getParentRoute: () => AppDashboardRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/dashboard": typeof AppDashboardRouteWithChildren;
  "/history": typeof AppHistoryRoute;
  "/api/healthz": typeof ApiHealthzRoute;
  "/movies/$movie": typeof AppMoviesMovieRoute;
  "/search/$query": typeof AppSearchQueryRoute;
  "/series/$series": typeof AppSeriesSeriesRoute;
  "/users/$user": typeof AppUsersUserRoute;
  "/dashboard/": typeof AppDashboardIndexRoute;
  "/dashboard/admin/system-accounts": typeof AppDashboardAdminSystemAccountsRoute;
  "/dashboard/playlists/new": typeof AppDashboardPlaylistsNewRoute;
  "/dashboard/series/new": typeof AppDashboardSeriesNewRoute;
  "/dashboard/videos/new": typeof AppDashboardVideosNewRoute;
  "/dashboard/playlists/": typeof AppDashboardPlaylistsIndexRoute;
  "/dashboard/series/": typeof AppDashboardSeriesIndexRoute;
  "/dashboard/videos/": typeof AppDashboardVideosIndexRoute;
  "/dashboard/playlists/$id/edit": typeof AppDashboardPlaylistsIdEditRoute;
  "/dashboard/series/$id/edit": typeof AppDashboardSeriesIdEditRoute;
  "/dashboard/videos/$id/edit": typeof AppDashboardVideosIdEditRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/history": typeof AppHistoryRoute;
  "/api/healthz": typeof ApiHealthzRoute;
  "/": typeof AppIndexRoute;
  "/movies/$movie": typeof AppMoviesMovieRoute;
  "/search/$query": typeof AppSearchQueryRoute;
  "/series/$series": typeof AppSeriesSeriesRoute;
  "/users/$user": typeof AppUsersUserRoute;
  "/dashboard": typeof AppDashboardIndexRoute;
  "/dashboard/admin/system-accounts": typeof AppDashboardAdminSystemAccountsRoute;
  "/dashboard/playlists/new": typeof AppDashboardPlaylistsNewRoute;
  "/dashboard/series/new": typeof AppDashboardSeriesNewRoute;
  "/dashboard/videos/new": typeof AppDashboardVideosNewRoute;
  "/dashboard/playlists": typeof AppDashboardPlaylistsIndexRoute;
  "/dashboard/series": typeof AppDashboardSeriesIndexRoute;
  "/dashboard/videos": typeof AppDashboardVideosIndexRoute;
  "/dashboard/playlists/$id/edit": typeof AppDashboardPlaylistsIdEditRoute;
  "/dashboard/series/$id/edit": typeof AppDashboardSeriesIdEditRoute;
  "/dashboard/videos/$id/edit": typeof AppDashboardVideosIdEditRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_app": typeof AppRouteWithChildren;
  "/login": typeof LoginRoute;
  "/register": typeof RegisterRoute;
  "/_app/dashboard": typeof AppDashboardRouteWithChildren;
  "/_app/history": typeof AppHistoryRoute;
  "/api/healthz": typeof ApiHealthzRoute;
  "/_app/": typeof AppIndexRoute;
  "/_app/movies/$movie": typeof AppMoviesMovieRoute;
  "/_app/search/$query": typeof AppSearchQueryRoute;
  "/_app/series/$series": typeof AppSeriesSeriesRoute;
  "/_app/users/$user": typeof AppUsersUserRoute;
  "/_app/dashboard/": typeof AppDashboardIndexRoute;
  "/_app/dashboard/admin/system-accounts": typeof AppDashboardAdminSystemAccountsRoute;
  "/_app/dashboard/playlists/new": typeof AppDashboardPlaylistsNewRoute;
  "/_app/dashboard/series/new": typeof AppDashboardSeriesNewRoute;
  "/_app/dashboard/videos/new": typeof AppDashboardVideosNewRoute;
  "/_app/dashboard/playlists/": typeof AppDashboardPlaylistsIndexRoute;
  "/_app/dashboard/series/": typeof AppDashboardSeriesIndexRoute;
  "/_app/dashboard/videos/": typeof AppDashboardVideosIndexRoute;
  "/_app/dashboard/playlists/$id/edit": typeof AppDashboardPlaylistsIdEditRoute;
  "/_app/dashboard/series/$id/edit": typeof AppDashboardSeriesIdEditRoute;
  "/_app/dashboard/videos/$id/edit": typeof AppDashboardVideosIdEditRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/register"
    | "/dashboard"
    | "/history"
    | "/api/healthz"
    | "/movies/$movie"
    | "/search/$query"
    | "/series/$series"
    | "/users/$user"
    | "/dashboard/"
    | "/dashboard/admin/system-accounts"
    | "/dashboard/playlists/new"
    | "/dashboard/series/new"
    | "/dashboard/videos/new"
    | "/dashboard/playlists/"
    | "/dashboard/series/"
    | "/dashboard/videos/"
    | "/dashboard/playlists/$id/edit"
    | "/dashboard/series/$id/edit"
    | "/dashboard/videos/$id/edit";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/register"
    | "/history"
    | "/api/healthz"
    | "/"
    | "/movies/$movie"
    | "/search/$query"
    | "/series/$series"
    | "/users/$user"
    | "/dashboard"
    | "/dashboard/admin/system-accounts"
    | "/dashboard/playlists/new"
    | "/dashboard/series/new"
    | "/dashboard/videos/new"
    | "/dashboard/playlists"
    | "/dashboard/series"
    | "/dashboard/videos"
    | "/dashboard/playlists/$id/edit"
    | "/dashboard/series/$id/edit"
    | "/dashboard/videos/$id/edit";
  id:
    | "__root__"
    | "/_app"
    | "/login"
    | "/register"
    | "/_app/dashboard"
    | "/_app/history"
    | "/api/healthz"
    | "/_app/"
    | "/_app/movies/$movie"
    | "/_app/search/$query"
    | "/_app/series/$series"
    | "/_app/users/$user"
    | "/_app/dashboard/"
    | "/_app/dashboard/admin/system-accounts"
    | "/_app/dashboard/playlists/new"
    | "/_app/dashboard/series/new"
    | "/_app/dashboard/videos/new"
    | "/_app/dashboard/playlists/"
    | "/_app/dashboard/series/"
    | "/_app/dashboard/videos/"
    | "/_app/dashboard/playlists/$id/edit"
    | "/_app/dashboard/series/$id/edit"
    | "/_app/dashboard/videos/$id/edit";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  RegisterRoute: typeof RegisterRoute;
  ApiHealthzRoute: typeof ApiHealthzRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/dashboard": {
      id: "/_app/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AppDashboardRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/history": {
      id: "/_app/history";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof AppHistoryRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/api/healthz": {
      id: "/api/healthz";
      path: "/api/healthz";
      fullPath: "/api/healthz";
      preLoaderRoute: typeof ApiHealthzRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/dashboard/": {
      id: "/_app/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof AppDashboardIndexRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
    "/_app/movies/$movie": {
      id: "/_app/movies/$movie";
      path: "/movies/$movie";
      fullPath: "/movies/$movie";
      preLoaderRoute: typeof AppMoviesMovieRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/search/$query": {
      id: "/_app/search/$query";
      path: "/search/$query";
      fullPath: "/search/$query";
      preLoaderRoute: typeof AppSearchQueryRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/series/$series": {
      id: "/_app/series/$series";
      path: "/series/$series";
      fullPath: "/series/$series";
      preLoaderRoute: typeof AppSeriesSeriesRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/users/$user": {
      id: "/_app/users/$user";
      path: "/users/$user";
      fullPath: "/users/$user";
      preLoaderRoute: typeof AppUsersUserRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/dashboard/admin/system-accounts": {
      id: "/_app/dashboard/admin/system-accounts";
      path: "/admin/system-accounts";
      fullPath: "/dashboard/admin/system-accounts";
      preLoaderRoute: typeof AppDashboardAdminSystemAccountsRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
    "/_app/dashboard/playlists/": {
      id: "/_app/dashboard/playlists/";
      path: "/playlists";
      fullPath: "/dashboard/playlists/";
      preLoaderRoute: typeof AppDashboardPlaylistsIndexRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
    "/_app/dashboard/playlists/new": {
      id: "/_app/dashboard/playlists/new";
      path: "/playlists/new";
      fullPath: "/dashboard/playlists/new";
      preLoaderRoute: typeof AppDashboardPlaylistsNewRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
    "/_app/dashboard/series/": {
      id: "/_app/dashboard/series/";
      path: "/series";
      fullPath: "/dashboard/series/";
      preLoaderRoute: typeof AppDashboardSeriesIndexRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
    "/_app/dashboard/series/new": {
      id: "/_app/dashboard/series/new";
      path: "/series/new";
      fullPath: "/dashboard/series/new";
      preLoaderRoute: typeof AppDashboardSeriesNewRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
    "/_app/dashboard/videos/": {
      id: "/_app/dashboard/videos/";
      path: "/videos";
      fullPath: "/dashboard/videos/";
      preLoaderRoute: typeof AppDashboardVideosIndexRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
    "/_app/dashboard/videos/new": {
      id: "/_app/dashboard/videos/new";
      path: "/videos/new";
      fullPath: "/dashboard/videos/new";
      preLoaderRoute: typeof AppDashboardVideosNewRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
    "/_app/dashboard/playlists/$id/edit": {
      id: "/_app/dashboard/playlists/$id/edit";
      path: "/playlists/$id/edit";
      fullPath: "/dashboard/playlists/$id/edit";
      preLoaderRoute: typeof AppDashboardPlaylistsIdEditRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
    "/_app/dashboard/series/$id/edit": {
      id: "/_app/dashboard/series/$id/edit";
      path: "/series/$id/edit";
      fullPath: "/dashboard/series/$id/edit";
      preLoaderRoute: typeof AppDashboardSeriesIdEditRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
    "/_app/dashboard/videos/$id/edit": {
      id: "/_app/dashboard/videos/$id/edit";
      path: "/videos/$id/edit";
      fullPath: "/dashboard/videos/$id/edit";
      preLoaderRoute: typeof AppDashboardVideosIdEditRouteImport;
      parentRoute: typeof AppDashboardRoute;
    };
  }
}

interface AppDashboardRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute;
  AppDashboardAdminSystemAccountsRoute: typeof AppDashboardAdminSystemAccountsRoute;
  AppDashboardPlaylistsNewRoute: typeof AppDashboardPlaylistsNewRoute;
  AppDashboardSeriesNewRoute: typeof AppDashboardSeriesNewRoute;
  AppDashboardVideosNewRoute: typeof AppDashboardVideosNewRoute;
  AppDashboardPlaylistsIndexRoute: typeof AppDashboardPlaylistsIndexRoute;
  AppDashboardSeriesIndexRoute: typeof AppDashboardSeriesIndexRoute;
  AppDashboardVideosIndexRoute: typeof AppDashboardVideosIndexRoute;
  AppDashboardPlaylistsIdEditRoute: typeof AppDashboardPlaylistsIdEditRoute;
  AppDashboardSeriesIdEditRoute: typeof AppDashboardSeriesIdEditRoute;
  AppDashboardVideosIdEditRoute: typeof AppDashboardVideosIdEditRoute;
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardAdminSystemAccountsRoute: AppDashboardAdminSystemAccountsRoute,
  AppDashboardPlaylistsNewRoute: AppDashboardPlaylistsNewRoute,
  AppDashboardSeriesNewRoute: AppDashboardSeriesNewRoute,
  AppDashboardVideosNewRoute: AppDashboardVideosNewRoute,
  AppDashboardPlaylistsIndexRoute: AppDashboardPlaylistsIndexRoute,
  AppDashboardSeriesIndexRoute: AppDashboardSeriesIndexRoute,
  AppDashboardVideosIndexRoute: AppDashboardVideosIndexRoute,
  AppDashboardPlaylistsIdEditRoute: AppDashboardPlaylistsIdEditRoute,
  AppDashboardSeriesIdEditRoute: AppDashboardSeriesIdEditRoute,
  AppDashboardVideosIdEditRoute: AppDashboardVideosIdEditRoute,
};

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
);

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren;
  AppHistoryRoute: typeof AppHistoryRoute;
  AppIndexRoute: typeof AppIndexRoute;
  AppMoviesMovieRoute: typeof AppMoviesMovieRoute;
  AppSearchQueryRoute: typeof AppSearchQueryRoute;
  AppSeriesSeriesRoute: typeof AppSeriesSeriesRoute;
  AppUsersUserRoute: typeof AppUsersUserRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppHistoryRoute: AppHistoryRoute,
  AppIndexRoute: AppIndexRoute,
  AppMoviesMovieRoute: AppMoviesMovieRoute,
  AppSearchQueryRoute: AppSearchQueryRoute,
  AppSeriesSeriesRoute: AppSeriesSeriesRoute,
  AppUsersUserRoute: AppUsersUserRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiHealthzRoute: ApiHealthzRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
