apiVersion: v1
kind: Service
metadata:
  name: vod
  labels:
    app.kubernetes.io/name: vod
    app.kubernetes.io/component: streaming
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vod
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
