apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: video-host

resources:
  - namespace.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ffmpeg-worker/deployment.yaml
  - vod/deployment.yaml
  - vod/service.yaml

commonLabels:
  app.kubernetes.io/part-of: video-host
